### ISSUE TITLE
Promises

### ISSUE THREAD

**Issue by juanmav** [OSGeo/ows.js#5]
Hi all, 

Some days ago I implemented async calls with promises. So the calls change from this:

**Older version**, sync and blocking method:

``` javascript
// GetRecords
var results = csw.GetRecords(1,10,filter);
console.log(results);
```

to this:

**New version**, async and no-blocking method:

``` javascript
// GetRecords
csw.GetRecords(1,10,filter).then(function(result){
        console.log(result)
    });
```

The code can by re-viewed at https://github.com/juanmav/ows.js/tree/promises

any comments?

Regards
JM

**Comment by tomkralidis** [comment]
@juanmav: nice.  Is this in master yet?  Are there any drawbacks to having async as the default pattern?

**Comment by juanmav** [comment]
@tomkralidis It isn't in the master yet. 

I think there are drawbacks with sync calls because these ones block the execution until the remote call is resolved. In a browser environment it will get the web app unresponsive until the call will be resolved.

**Comment by tomkralidis** [comment]
@juanmav thanks for the info.  I'm +1 for async to be added to the codebase.
